---
sidebar: sidebar 
permalink: concept_api_versions.html 
keywords: rest api, deploy rest api, rest, version, versioning 
summary: La API REST incluida con ONTAP Select Deploy tiene asignado un número de versión. Este número es independiente del número de versión de Deploy. Debe conocer la versión de la API incluida con su versión de Deploy y cómo esta podría afectar su uso de la API. 
---
= Control de versiones de la API de implementación de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La API REST incluida con ONTAP Select Deploy tiene asignado un número de versión. Este número es independiente del número de versión de Deploy. Debe conocer la versión de la API incluida con su versión de Deploy y cómo esta podría afectar su uso de la API.

La versión actual de la utilidad de administración Deploy incluye la versión 3 de la API REST. Las versiones anteriores de la utilidad Deploy incluyen las siguientes versiones de la API:

Implementar 2.8 y posteriores:: ONTAP Select Deploy 2.8 y todas las versiones posteriores incluyen la versión 3 de la API REST.
Implementar 2.7.2 y anteriores:: ONTAP Select Deploy 2.7.2 y todas las versiones anteriores incluyen la versión 2 de la API REST.



NOTE: Las versiones 2 y 3 de la API REST no son compatibles. Si actualiza a Deploy 2.8 o posterior desde una versión anterior que incluye la versión 2 de la API, debe actualizar todo el código existente que acceda directamente a la API, así como cualquier script que utilice la interfaz de línea de comandos.
