---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partir de ONTAP Select 9.15.1, puede aumentar el tamaño de un clúster existente de seis a ocho nodos y disminuir el tamaño del clúster de ocho a seis nodos. 
---
= Expandir o contraer un clúster de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP Select 9.15.1, puede aumentar el tamaño de un clúster existente de seis a ocho nodos y disminuir el tamaño del clúster de ocho a seis nodos.

Las siguientes expansiones y contracciones de clúster no son compatibles:

* Expansiones de clústeres de uno, dos o cuatro nodos a clústeres de seis u ocho nodos.
* Contracciones de grupos de seis u ocho nodos a grupos de uno, dos o cuatro nodos.


[NOTE]
====
Para cambiar la cantidad de nodos de un clúster a un tamaño que no sea compatible con la expansión o contracción del clúster, debe realizar las siguientes tareas:

. Implemente un nuevo clúster de múltiples nodos mediante el uso de link:task_cli_deploy_cluster.html["CLI"] o el link:task_deploy_cluster.html["interfaz de usuario web"] proporcionado con la utilidad de administración ONTAP Select Deploy.
. Si corresponde, migre los datos al nuevo clúster mediante link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Replicación de SnapMirror"^] .


====
Puede iniciar los procedimientos de expansión y contracción del clúster desde ONTAP Select Deploy mediante la CLI, la API o la interfaz web.



== Consideraciones sobre hardware y almacenamiento

Las funcionalidades de expansión y contracción del clúster están restringidas de las siguientes maneras:

* La compatibilidad se limita a clústeres creados en hosts con hipervisor ESX. Las siguientes versiones de ESX son compatibles con ONTAP Select 9.15.1 y versiones posteriores:
+
** ESXi 8.0 U3
** ESXi 8.0 U2
** ESXi 8.0 U1
** ESXi 8.0 GA
** ESXi 7.0 U3
** ESXi 7.0






== Ampliar el clúster

Puede aumentar el tamaño de un clúster existente de seis nodos a uno de ocho nodos con la función de expansión de clúster.

.Acerca de esta tarea
Como preparación para el procedimiento de expansión del clúster, se agregan nuevos hosts ESX al inventario y se asignan los detalles de los nuevos nodos. Antes de iniciar el proceso de expansión del clúster, se realiza una comprobación previa de la red para verificar la red interna seleccionada.

.Antes de empezar
* Al implementar un clúster multinodo, debe familiarizarse con el verificador de conectividad de red. Puede ejecutarlo mediante el link:task_adm_connectivity.html["interfaz de usuario web"] o el link:task_cli_connectivity.html["CLI"] .
* Verifique que tenga los detalles de la licencia para los nuevos nodos.


.Pasos
. Sign in en la interfaz de usuario web de la utilidad de implementación utilizando la cuenta de administrador.
. Seleccione la pestaña *Clúster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, seleccione el ícono de engranaje a la derecha de la página y seleccione *Expandir clúster*.
. Vaya a la sección *HA Pair 4*.
. Seleccione los detalles de configuración del par de alta disponibilidad (HA) para el cuarto par de HA, incluidos:
+
** Tipo de instancia
** Nombres de nodos
** Hosts de hipervisor asociados
** Direcciones IP de nodos
** Licencias
** Configuración de red
** Configuración de almacenamiento (tipo RAID y grupos de almacenamiento)


. Seleccione *Guardar par HA* para guardar los detalles de configuración.
. Proporcione las credenciales de ONTAP , luego seleccione *Expandir clúster*.
. Seleccione *Siguiente* y ejecute la comprobación previa de la red seleccionando *Ejecutar*.
+
La verificación previa de la red valida que la red interna seleccionada para el tráfico del clúster ONTAP esté funcionando correctamente.

. Seleccione *Expandir clúster* para comenzar el proceso de expansión del clúster y luego seleccione *Aceptar* en el cuadro de diálogo.
+
La expansión del clúster puede tardar hasta 45 minutos.

. Supervise el proceso de expansión del clúster de varios pasos para confirmar que el clúster se expandió correctamente.
. Consulte la pestaña *Eventos* para obtener actualizaciones periódicas sobre el progreso de la operación. La página se actualiza automáticamente a intervalos regulares.


.Después de terminar
Después de expandir el clúster, debe realizar una copia de seguridad de los datos de configuración de ONTAP Select Deploy.



== Contraer el cluster

Puede reducir el tamaño de un clúster existente de ocho nodos a uno de seis nodos con la función de contracción del clúster.

.Acerca de esta tarea
Se selecciona el par de nodos HA deseado en el clúster para prepararlo para la contracción del clúster durante el procedimiento.

.Pasos
. Sign in en la interfaz de usuario web de la utilidad de implementación utilizando la cuenta de administrador.
. Seleccione la pestaña *Clúster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, seleccione el ícono de engranaje a la derecha de la página, luego seleccione *Contratar clúster*.
. Seleccione los detalles de configuración del par HA para cualquier par HA que desee eliminar y proporcione las credenciales de ONTAP , luego seleccione *Clúster de contrato*.
+
La contracción del clúster puede tardar hasta 30 minutos.

. Supervise el proceso de contracción del clúster de varios pasos para confirmar que el clúster se contrajo correctamente.
. Consulte la pestaña *Eventos* para obtener actualizaciones periódicas sobre el progreso de la operación. La página se actualiza automáticamente a intervalos regulares.

