---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Puede actualizar una máquina virtual de utilidad de implementación existente en el lugar mediante la interfaz de línea de comandos. 
---
= Actualizar una instancia de ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede actualizar una máquina virtual de utilidad de implementación existente en el lugar mediante la interfaz de línea de comandos.



== Antes de empezar

Asegúrese de que Deploy no se utilice para realizar otras tareas durante la actualización. Consulte las notas de la versión actual para obtener información y conocer las restricciones sobre la actualización de la utilidad Deploy.


NOTE: Si tiene instalada una instancia anterior de la utilidad de administración ONTAP Select Deploy, debe actualizarla a la versión actual. El nodo ONTAP Select y el componente ONTAP Select Deploy se actualizan de forma independiente. Consulte link:concept_adm_upgrading_nodes.html["Actualizar los nodos ONTAP Select"^] Para más detalles.



== Descargar el paquete de actualización

Para iniciar el proceso de actualización, debe descargar el archivo de actualización de la máquina virtual de implementación correspondiente desde el sitio de soporte de NetApp . El paquete de actualización está en un único archivo comprimido.

.Pasos
. Acceder a la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] utilizando un navegador web y seleccione *Descargas* en el menú Descargas.
. Desplácese hacia abajo y seleccione * ONTAP Select Deploy Upgrade*.
. Seleccione la versión deseada del paquete de actualización.
. Revise el Acuerdo de licencia de usuario final (EULA) y seleccione *Aceptar y continuar*.
. Seleccione y descargue el paquete apropiado, respondiendo a todas las indicaciones según sea necesario para su entorno.




== Subir el paquete a la máquina virtual de implementación

Después de adquirir el paquete de actualización, debe cargar el archivo en la máquina virtual de implementación.

.Antes de empezar
Debe tener el archivo de actualización disponible en su estación de trabajo local. También debe tener la contraseña de la cuenta de administrador.

.Acerca de estas tareas
Esta tarea describe un método para cargar el archivo a la máquina virtual de implementación. Es posible que existan otras opciones más adecuadas para su entorno.

.Pasos
. En un shell de comandos en su estación de trabajo local, use la utilidad scp para cargar el archivo de imagen en la máquina virtual de implementación.
+
Ejemplo

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Resultado
El archivo de actualización se almacena en el directorio de inicio del usuario administrador.



== Aplicar el paquete de actualización

Una vez cargado el archivo de actualización en la máquina virtual de implementación, puede aplicar la actualización.

.Antes de empezar
Debe saber en qué directorio se encuentra el archivo de actualización en la máquina virtual de la utilidad de implementación. Además, asegúrese de que la implementación no se utilice para realizar otras tareas mientras se realiza la actualización.

.Pasos
. Sign in en la CLI de la utilidad de implementación mediante SSH con la cuenta de administrador.
. Realice la actualización utilizando la ruta de directorio y el nombre de archivo adecuados:
+
`deploy upgrade -package-path FILEPATH`

+
Ejemplo

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Después de terminar
Antes de completar la actualización, se le solicitará que cree una copia de seguridad de la configuración de la máquina virtual de implementación. Además, debe borrar la caché del navegador para poder ver las páginas de implementación recién creadas.
